
output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: FGM - FHIR&reg; API for Spine 2 FGM Service
# this appears on the top navigation bar next to the home button

site_title: FGM Service
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: NHS Digital
# this appears in the footer

#github_editme_path: /edit/gh-pages/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

#disqus: true
disqus_shortname: nhsconnect

#gitter: false
#gitter_room: gpconnect/Lobby

#tiny_letter: true
#tiny_letter_username: nhsconnectapi

# twitter: true
# twitter_username: nhsconnectapi
# twitter_site_hashtags: GPConnect

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4007
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - pages/development/development_github_repositories.md
# these are the files and directories that jekyll will exclude from the build

feedback_email: interoperability@nhs.net
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  developer-journey:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: overview_sidebar

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: overview_sidebar

# these are defaults used for the frontmatter for these file types

sidebars:
- overview_sidebar
- designprinciples_sidebar
- accessrecord_sidebar
- appointments_sidebar
- tasks_sidebar

description: "The FGM Risk Indication System provides the ability to identify (flag) and share an identifier of vulnerable girls and women at risk of FGM (Female Genital Mutilation)."
#old description "GP Connect aims to support better clinical care by opening up information and data held within GP Practice IT systems for use across health and social care. The GP Connect vision will be achieved by standardising integration and simplifying the operating model."
# the description is used in the feed.xml file

sitemap: true

# needed for sitemap.xml file only
#url: https://nhsconnect.github.io/gpconnect
url: https://nhsconnect.github.io/fgm

#repository: nhsconnect/fgm
repository: nhsconnect/fgm-risk-indication-service 

gist:
  noscript: false

plugins:
   - jekyll-github-metadata
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-gist
   - nokogiri
